# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('ts', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 8, 12193))),
                ('content', models.TextField()),
                ('parent', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('parent_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
