# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_ts',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 14, 648193)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 14, 648193)),
        ),
    ]
