# Generated by Django 2.1.3 on 2018-11-14 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20181113_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_ts',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 13, 22, 38, 576122)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 13, 22, 38, 575122)),
        ),
    ]
