# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '__first__'),
        ('album', '0002_auto_20181113_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.IntegerField(default=0)),
                ('object_id', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 14, 651193))),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_avatar', models.CharField(blank=True, max_length=100)),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(blank=True, max_length=1000)),
                ('content', models.CharField(blank=True, max_length=10000)),
                ('following_user_id', models.IntegerField(default=0)),
                ('following_user_name', models.CharField(blank=True, max_length=200)),
                ('follower_user_id', models.IntegerField(default=0)),
                ('follower_user_name', models.CharField(blank=True, max_length=200)),
                ('is_like', models.BooleanField(default=False)),
                ('photos', models.ManyToManyField(to='album.Photo')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
