# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_type', models.IntegerField()),
                ('notify_id', models.IntegerField()),
                ('object_type', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('notified_user', models.IntegerField()),
                ('notifier', models.IntegerField()),
                ('ts', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 37, 725193))),
                ('status', models.IntegerField(default=0)),
                ('notifier_name', models.CharField(blank=True, max_length=100)),
                ('notifier_avatar', models.URLField(blank=True)),
                ('object_title', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
