# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ts', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 27, 225193))),
            ],
        ),
    ]
