# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.IntegerField()),
                ('ts', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 51, 824193))),
                ('content', models.TextField()),
                ('title', models.CharField(default='New Post', max_length=100)),
                ('excerpt', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('comment_status', models.IntegerField(default=0)),
                ('pwd', models.CharField(blank=True, max_length=100)),
                ('lastts', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('album', models.IntegerField(default=0)),
                ('cover', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
