# Generated by Django 2.1.3 on 2018-11-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('add_ts', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 43, 58, 166193))),
                ('cover', models.URLField(blank=True)),
            ],
        ),
    ]
